routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home');
Route::post('public-message', 'ContactController@messageStore')->name('public-message.store');

Auth::routes();
Route::get('hub-register', 'HubController@registerHub')->name('hub.register');
Route::get('hub-identy-img/{id}', 'HubController@downloadIdentyImg')->name('hub-identy-img');
// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/pricing', 'HomeController@pricing')->name('pricing');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/contact', 'HomeController@contact')->name('contact');

Route::middleware('auth')->group(function () {
    Route::resource('user', 'UserController');

    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('manage/{id}', 'DashboardController@userManage')->name('user.manage');

    Route::get('/home-components', 'HomeController@homeComponents')->name('home-components');

    Route::resource('role', 'RoleController');

    Route::resource('merchants', 'MerchantController');
    Route::get('merchant-requests', 'MerchantController@merchantRequest')->name('merchant-requests');
    Route::get('merchant-inactive', 'MerchantController@merchantInactive')->name('merchants.inactive');
    Route::get('get-merchants-admin', 'MerchantController@getIndexAdmin')->name('get-merchants-admin');
    Route::get('merchant-active/{id}', 'MerchantController@merchantActive')->name('merchant.active');

    Route::resource('special-merchants', 'SpecialMerchantController');

    Route::resource('agents', 'HubController');
    Route::get('agent-requests', 'HubController@agentRequest')->name('agent-requests');
    Route::get('agent-inactive', 'HubController@agentInactive')->name('agents.inactive');
    Route::get('get-agents-admin', 'HubController@getIndexAdmin')->name('get-agents-admin');
    Route::get('agent-active/{id}', 'HubController@agentActive')->name('agent.active');
    Route::get('manage-agent/{id}', 'HubController@userManage')->name('manage.agent');
    Route::post('agent-tag', 'HubController@assign')->name('agent.tag');
    Route::post('manage-agents-admin', 'HubController@manageDelivery')->name('manage-agents-admin');
    Route::get('all-deliveries-agent', 'HubController@indexAll')->name('all.deliveries.agent');
    Route::get('get-all-deliveries-agent', 'HubController@getAll')->name('get-all-deliveries-agent');

    Route::resource('special-agents', 'SpecialAgentController');

    Route::resource('customers', 'CustomerController');
    Route::get('customers-requests', 'CustomerController@merchantRequest')->name('customers-requests');
    Route::get('customers-active/{id}', 'CustomerController@merchantActive')->name('customers.active');

    Route::resource('admin-services', 'ServiceController');

    Route::resource('admin-client', 'ClientController');

    Route::resource('admin-inter-city-rates', 'InterCityRateController');
    Route::resource('admin-rate-info', 'AddRateInfoController');

    Route::resource('admin-about', 'AboutUsController');
    Route::resource('admin-about-card', 'AboutUsCardController');

    Route::resource('districts', 'DistrictController');

    Route::resource('areas', 'AreaController');



    Route::resource('deliveries', 'DeliveryController');
    Route::get('print/delivery-info/{id}', 'DeliveryController@printInfoDelivery')->name('deliveries.info.print');
    Route::get('print/pickup-info/{id}', 'DeliveryController@printInfoPickup')->name('deliveries.pickup.print');
    Route::get('deliveries-admin', 'DeliveryController@indexAdmin')->name('deliveries-admin');
    Route::get('all-deliveries-admin', 'DeliveryController@indexAll')->name('all.deliveries');
    Route::get('get-deliveries-admin', 'DeliveryController@getIndexAdmin')->name('get-deliveries-admin');
    Route::get('get-deliveries-agent', 'DeliveryController@getIndexAgent')->name('get-deliveries-agent');
    Route::get('get-all-deliveries-admin', 'DeliveryController@getAll')->name('get-all-deliveries-admin');
    Route::post('manage-deliveries-admin', 'DeliveryController@manageDelivery')->name('manage-deliveries-admin');
    Route::post('get-delivery-info', 'DeliveryController@getDeliveryInfo')->name('get-delivery-info');
    Route::post('admin-delivered', 'DeliveryController@delivered')->name('admin.delivered');
    Route::post('admin-pickup', 'DeliveryController@pickup')->name('admin.pickup');
    Route::post('admin-cancel', 'DeliveryController@cancel')->name('admin.cancel');
    Route::post('admin-hold', 'DeliveryController@hold')->name('admin.hold');
    Route::post('admin-no-status', 'DeliveryController@noStatus')->name('admin.no.status');
    Route::post('admin-paid', 'DeliveryController@paid')->name('admin.paid');
    Route::post('admin-unpaid', 'DeliveryController@unPaid')->name('admin.unpaid');
    Route::post('deliveries-delete', 'DeliveryController@delete')->name('deliveries.delete');

    Route::get('admin-delivery-statuses', 'DeliveryController@statuses')->name('admin.statuses');

    Route::get('invoices', 'InvoiceController@index')->name('invoices.index');
    Route::get('get-invoices', 'InvoiceController@getInvoice')->name('get.invoices');
    Route::get('invoice/delete/{id}', 'InvoiceController@delete')->name('invoice.delete');
    Route::get('invoice/{id}', 'InvoiceController@show')->name('invoice.show');
    Route::post('delivery/invoice', 'InvoiceController@getInvoiceInfo')->name('delivery.invoice');
    Route::post('delivery/invoice/agent', 'InvoiceController@getInvoiceInfoAgent')->name('delivery.invoice.agent');
    Route::get('invoice/pdf-export/{id}', 'InvoiceController@export')->name('export.pdf');

    Route::resource('payment-requests', 'PaymentRequestsController');
    Route::get('get-payment-requests', 'PaymentRequestsController@getRequest');
    Route::post('admin.request.solve', 'PaymentRequestsController@solveRequest')->name('admin.request.solve');
    Route::post('admin.request.pending', 'PaymentRequestsController@pendingRequest')->name('admin.request.pending');

    Route::resource('authority-teams', 'AuthorityTeamController');

    Route::get('admin-contact', 'ContactController@index')->name('admin-contact');
    Route::post('admin-email-store', 'ContactController@emailStore')->name('admin-email.store');
    Route::post('admin-phone-store', 'ContactController@phoneStore')->name('admin-phone.store');
    Route::post('admin-address-store', 'ContactController@addressStore')->name('admin-address.store');
    Route::delete('admin-email-delete/{id}', 'ContactController@emailDestroy')->name('admin-email.destroy');
    Route::delete('admin-phone-delete/{id}', 'ContactController@phoneDestroy')->name('admin-phone.destroy');
    Route::delete('admin-address-delete/{id}', 'ContactController@addressDestroy')->name('admin-address.destroy');
    Route::get('admin-email-edit/{id}', 'ContactController@emailEdit')->name('admin-email.edit');
    Route::get('admin-phone-edit/{id}', 'ContactController@phoneEdit')->name('admin-phone.edit');
    Route::get('admin-address-edit/{id}', 'ContactController@addressEdit')->name('admin-address.edit');
    Route::put('admin-email-update/{id}', 'ContactController@emailUpdate')->name('admin-email.update');
    Route::put('admin-phone-update/{id}', 'ContactController@phoneUpdate')->name('admin-phone.update');
    Route::put('admin-address-update/{id}', 'ContactController@addressUpdate')->name('admin-address.update');

    Route::get('messages', 'PublicMessageController@index')->name('messages');

});

resources/views/layouts/backend/agents/active-modal.blade.php
<div class="modal fade" tabindex="-1" role="dialog" id="confirm" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <p>Are you sure you want to Active?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-success" id="delete-btn">Yes, Active</button>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/backend/agents/agents-menu.blade.php
<div class="card-header card-header-info">
    <div class="nav-tabs-navigation">
        <div class="nav-tabs-wrapper">
          <ul class="nav nav-tabs" data-tabs="tabs">
            <li class="nav-item">
            <a class="nav-link {{ (request()->is('agent-requests')) ? 'active' : '' }}" href="{{url('agent-requests')}}">
                Agent Request <span class="badge badge-pill badge-warning">{{$aReq}}</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {{ (request()->is('agents')) ? 'active' : '' }}" href="{{route('agents.index')}}">
                Active Agents
              </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ (request()->is('agent-inactive')) ? 'active' : '' }}" href="{{route('agents.inactive')}}">
                  Inactive
                </a>
              </li>
          </ul>
        </div>
      </div>
</div>

resources/views/layouts/backend/agents/create-modal.blade.php
<div class="modal fade create" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Create New Role</h5>
            <button style="color: white" type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          </div>


        <div class="modal-body">
            <form action="{{route('role.store')}}" method="POST">
                @csrf
                    <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                        <label class="bmd-label-floating">Role Name <span style="color: red">*</span></label>
                        <input name="title" type="text" class="form-control" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                        <label class="bmd-label-floating">Code</label>
                        <input name="code" type="text" class="form-control">
                        </div>
                    </div>
                    </div>

                    <button type="submit" class="btn btn-primary pull-right">Create</button>
                    <div class="clearfix"></div>
            </form>
        {{-- form End--}}

        </div>
      </div>
    </div>
  </div>

resources/views/layouts/backend/agents/delete-modal.blade.php
<div class="modal fade" tabindex="-1" role="dialog" id="confirm" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <p>Are you sure you want to delete this?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-danger" id="delete-btn">Delete</button>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/backend/agents/inactive.blade.php
@extends('layouts.backend.layouts.app')
@section('content')
<div class="container-fluid">
    <div class="row">
      {{-- <div class="col-md-8"> --}}
        <div class="card">
          @include('layouts.backend.agents.agents-menu')
          <div class="card-body table-responsive">
              {{-- <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target=".create">Create New Role</button> --}}
              <div class="clearfix"></div>
              <br>
                @php
                 $i = 1;
                @endphp
                <table class="table table-bordered table-hover" data-form="deleteForm">
                    <thead class="card-header-primary no-shadow">
                      <tr style="text-align: center">
                        <th scope="col">SL</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Shop Name</th>
                        <th scope="col">Address</th>
                        <th scope="col">Phone</th>
                        <th scope="col">City</th>
                        <th scope="col">Status</th>
                        <th scope="col">Registered At</th>
                        <th scope="col">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                    @foreach ($datas as $data)
                        <tr style="text-align: center">
                            <td>{{$i++}}</td>
                            <td>{{$data->name}}</td>
                            <td>{{$data->email}}</td>
                            <td>{{$data->shop_name}}</td>
                            <td>{{$data->address}}</td>
                            <td>{{$data->phone}}</td>
                            <td>{{$data->district->title}}</td>
                            <td>
                                @if ($data->status == 1)
                                <span class="badge badge-pill badge-success">Active</span>
                                @elseif($data->status == 2)
                                <span class="badge badge-pill badge-danger">Inactive</span>
                                @endif
                            </td>
                            <td>{{$data->updated_at}}</td>
                            <td class="td-actions">
                                <a class="btn btn-success" href="{{ url('agent-active/'.$data->id) }}">
                                    Active
                                </a>
                                {{-- <a class="btn btn-primary btn-link" href="{{ route('merchants.edit', $data->id) }}">
                                    <i class="material-icons">edit</i>
                                </a> --}}

                                {{-- <form class="form-delete" action="{{ route('role.destroy', $data->id) }}" method="POST">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button type="submit" title="Delete" class="delete btn btn-danger btn-link">
                                        <i class="material-icons">close</i>
                                      </button>
                                </form> --}}


                              </td>
                        </tr>
                    @endforeach
                      </tr>
                    </tbody>
                  </table>
            </div>
          </div>
        {{-- </div> --}}
      </div>
    </div>


@include('layouts.backend.merchants.active-modal')
@include('layouts.backend.merchants.create-modal')

@endsection

@push('scripts')

@endpush

resources/views/layouts/backend/agents/index.blade.php
@extends('layouts.backend.layouts.app')
@section('content')
<div class="container-fluid">
    <div class="row">
      {{-- <div class="col-md-8"> --}}
        <div class="card">
          @include('layouts.backend.agents.agents-menu')
          <div class="card-body table-responsive">
              {{-- <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target=".create">Create New Role</button> --}}
              <div class="clearfix"></div>
              <br>
              @php
               $i = 1;
              @endphp
              <table class="table table-bordered" class="table-hover" id="get-agents-admin"  width="100%">
                  <thead>
                  <tr style="text-align: center">
                      <th scope="col">SL</th>
                      <th scope="col">Action</th>
                      <th scope="col">Name</th>
                      <th scope="col">Code</th>
                      <th scope="col">Email</th>
                      <th scope="col">Service Name</th>
                      <th scope="col">Address</th>
                      <th scope="col">Phone 1</th>
                      <th scope="col">Phone 2</th>
                      <th scope="col">City</th>
                      <th scope="col">License No.</th>
                      <th scope="col">NID/Passport/Birth Certificate No.</th>
                      <th scope="col">NID/Passport/Birth Certificate Image</th>
                      <th scope="col">Status</th>
                      <th scope="col">Registered At</th>
                      <th scope="col">Activated At</th>
                  </tr>
                  </thead>
              </table>
          </div>
        </div>
      {{-- </div> --}}
    </div>
  </div>


@include('layouts.backend.agents.delete-modal')
{{--@include('layouts.backend.agents.view-admin')--}}

@endsection

@push('scripts')
  <script>
      $(function() {
          $('#get-agents-admin').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                // scrollX: true,
                // paging: false,
              ajax: '{{ url('get-agents-admin') }}',
              columns: [
                  { data: 'DT_RowIndex', name: 'id', orderable: false },
                  {data: 'action', name: 'action', orderable: false,
                      render:
                          function(data, type, row) {
                              return '<div class="action-btn">'+
                                  '<a class="btn btn-primary btn-link" href="agents/'+row.id+'/edit"><i class="material-icons">edit</i></a>'+
                                  '<a class="btn btn-info" href="manage-agent/'+row.id+'">Manage</a>'+
                                  '</div>';

                          }
                  },
                  { data: 'name', name: 'name', orderable: false },
                  { data: 'code', name: 'code', orderable: false },
                  { data: 'email', name: 'email', orderable: false },
                  { data: 'service_name', name: 'service_name', orderable: false },
                  { data: 'address', name: 'address', orderable: false },
                  { data: 'phone', name: 'phone', orderable: false },
                  { data: 'phone2', name: 'phone2', orderable: false },
                  { data: 'city', name: 'city', orderable: false },
                  { data: 'license', name: 'license', orderable: false },
                  { data: 'identy_no', name: 'identy_no', orderable: false },
                  { data: 'identy_image', name: 'identy_image', orderable: false ,
                      render:
                          function(data, type, row) {
                              if(data != null) {
                                  return '<a href="hub-identy-img/' + data + '">Download</a>'
                              }else {
                                  return '';
                              }
                          }
                  },
                  { data: 'status', name: 'status', orderable: false ,
                      render:
                          function(data, type, row) {
                              if(row.status == 1){
                                  return '<span class="badge badge-pill badge-success">Active</span>';
                              }

                          }
                  },
                  { data: 'registered_at', name: 'registered_at', orderable: false },
                  { data: 'activated_at', name: 'activated_at', orderable: false },
                //   { data: 'action', name: 'action', orderable: false },
              ],

          });

      });
  </script>
@endpush

resources/views/layouts/backend/agents/requests.blade.php
@extends('layouts.backend.layouts.app')
@section('content')
<div class="container-fluid">
    <div class="row">
      {{-- <div class="col-md-8"> --}}
        <div class="card">
          @include('layouts.backend.agents.agents-menu')
          <div class="card-body table-responsive">
              {{-- <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target=".create">Create New Role</button> --}}
              <div class="clearfix"></div>
              <br>
                @php
                 $i = 1;
                @endphp
                <table class="table table-bordered table-hover" data-form="deleteForm">
                    <thead class="card-header-primary no-shadow">
                      <tr style="text-align: center">
                        <th scope="col">SL</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Service Name</th>
                        <th scope="col">Address</th>
                        <th scope="col">Phone 1</th>
                        <th scope="col">Phone 2</th>
                        <th scope="col">City</th>
                        <th scope="col">License No.</th>
                        <th scope="col">NID/Passport/Birth Certificate No.</th>
                        <th scope="col">NID/Passport/Birth Certificate Image</th>
                        <th scope="col">Status</th>
                        <th scope="col">Registered At</th>
                        <th scope="col">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                    @foreach ($datas as $data)
                        <tr style="text-align: center">
                            <td>{{$i++}}</td>
                            <td>{{$data->name}}</td>
                            <td>{{$data->email}}</td>
                            <td>{{$data->hubInfo->service_name}}</td>
                            <td>{{$data->address}}</td>
                            <td>{{$data->phone}}</td>
                            <td>{{$data->hubInfo->phone2}}</td>
                            <td>{{$data->district->title}}</td>
                            <td>{{$data->hubInfo->license}}</td>
                            <td>{{$data->hubInfo->identy_no}}</td>
                            <td>
                                <a href="{{route('hub-identy-img', ['id'=>$data->hubInfo->identy_image])}}">Download</a>
                            </td>
                            <td>
                                @if ($data->status == 1)
                                <span class="badge badge-pill badge-success">Active</span>
                                @elseif($data->status == 2)
                                <span class="badge badge-pill badge-danger">Inactive</span>
                                @endif
                            </td>
                            <td>{{$data->updated_at}}</td>
                            <td class="td-actions">
                                <a class="btn btn-success" href="{{ url('agent-active/'.$data->id) }}">
                                    Active
                                </a>
                                {{-- <a class="btn btn-primary btn-link" href="{{ route('merchants.edit', $data->id) }}">
                                    <i class="material-icons">edit</i>
                                </a> --}}

                                {{-- <form class="form-delete" action="{{ route('role.destroy', $data->id) }}" method="POST">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button type="submit" title="Delete" class="delete btn btn-danger btn-link">
                                        <i class="material-icons">close</i>
                                      </button>
                                </form> --}}


                              </td>
                        </tr>
                    @endforeach
                      </tr>
                    </tbody>
                  </table>
            </div>
          </div>
        {{-- </div> --}}
      </div>
    </div>


@include('layouts.backend.merchants.active-modal')
@include('layouts.backend.merchants.create-modal')

@endsection

@push('scripts')

@endpush
@push('styles')
    <style>
        .zoom:hover {
            -ms-transform: scale(3); /* IE 9 */
            -webkit-transform: scale(3); /* Safari 3-8 */
            transform: scale(3);
        }
    </style>
@endpush