routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home');
Route::post('public-message', 'ContactController@messageStore')->name('public-message.store');

Auth::routes();
Route::get('hub-register', 'HubController@registerHub')->name('hub.register');
Route::get('hub-identy-img/{id}', 'HubController@downloadIdentyImg')->name('hub-identy-img');
// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/pricing', 'HomeController@pricing')->name('pricing');
Route::get('/services', 'HomeController@services')->name('services');
Route::get('/contact', 'HomeController@contact')->name('contact');

Route::middleware('auth')->group(function () {
    Route::resource('user', 'UserController');

    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('manage/{id}', 'DashboardController@userManage')->name('user.manage');

    Route::get('/home-components', 'HomeController@homeComponents')->name('home-components');

    Route::resource('role', 'RoleController');

    Route::resource('merchants', 'MerchantController');
    Route::get('merchant-requests', 'MerchantController@merchantRequest')->name('merchant-requests');
    Route::get('merchant-inactive', 'MerchantController@merchantInactive')->name('merchants.inactive');
    Route::get('get-merchants-admin', 'MerchantController@getIndexAdmin')->name('get-merchants-admin');
    Route::get('merchant-active/{id}', 'MerchantController@merchantActive')->name('merchant.active');

    Route::resource('special-merchants', 'SpecialMerchantController');

    Route::resource('agents', 'HubController');
    Route::get('agent-requests', 'HubController@agentRequest')->name('agent-requests');
    Route::get('agent-inactive', 'HubController@agentInactive')->name('agents.inactive');
    Route::get('get-agents-admin', 'HubController@getIndexAdmin')->name('get-agents-admin');
    Route::get('agent-active/{id}', 'HubController@agentActive')->name('agent.active');
    Route::get('manage-agent/{id}', 'HubController@userManage')->name('manage.agent');
    Route::post('agent-tag', 'HubController@assign')->name('agent.tag');
    Route::post('manage-agents-admin', 'HubController@manageDelivery')->name('manage-agents-admin');
    Route::get('all-deliveries-agent', 'HubController@indexAll')->name('all.deliveries.agent');
    Route::get('get-all-deliveries-agent', 'HubController@getAll')->name('get-all-deliveries-agent');

    Route::resource('special-agents', 'SpecialAgentController');

    Route::resource('customers', 'CustomerController');
    Route::get('customers-requests', 'CustomerController@merchantRequest')->name('customers-requests');
    Route::get('customers-active/{id}', 'CustomerController@merchantActive')->name('customers.active');

    Route::resource('admin-services', 'ServiceController');

    Route::resource('admin-client', 'ClientController');

    Route::resource('admin-inter-city-rates', 'InterCityRateController');
    Route::resource('admin-rate-info', 'AddRateInfoController');

    Route::resource('admin-about', 'AboutUsController');
    Route::resource('admin-about-card', 'AboutUsCardController');

    Route::resource('districts', 'DistrictController');

    Route::resource('areas', 'AreaController');



    Route::resource('deliveries', 'DeliveryController');
    Route::get('print/delivery-info/{id}', 'DeliveryController@printInfoDelivery')->name('deliveries.info.print');
    Route::get('print/pickup-info/{id}', 'DeliveryController@printInfoPickup')->name('deliveries.pickup.print');
    Route::get('deliveries-admin', 'DeliveryController@indexAdmin')->name('deliveries-admin');
    Route::get('all-deliveries-admin', 'DeliveryController@indexAll')->name('all.deliveries');
    Route::get('get-deliveries-admin', 'DeliveryController@getIndexAdmin')->name('get-deliveries-admin');
    Route::get('get-deliveries-agent', 'DeliveryController@getIndexAgent')->name('get-deliveries-agent');
    Route::get('get-all-deliveries-admin', 'DeliveryController@getAll')->name('get-all-deliveries-admin');
    Route::post('manage-deliveries-admin', 'DeliveryController@manageDelivery')->name('manage-deliveries-admin');
    Route::post('get-delivery-info', 'DeliveryController@getDeliveryInfo')->name('get-delivery-info');
    Route::post('admin-delivered', 'DeliveryController@delivered')->name('admin.delivered');
    Route::post('admin-pickup', 'DeliveryController@pickup')->name('admin.pickup');
    Route::post('admin-cancel', 'DeliveryController@cancel')->name('admin.cancel');
    Route::post('admin-hold', 'DeliveryController@hold')->name('admin.hold');
    Route::post('admin-no-status', 'DeliveryController@noStatus')->name('admin.no.status');
    Route::post('admin-paid', 'DeliveryController@paid')->name('admin.paid');
    Route::post('admin-unpaid', 'DeliveryController@unPaid')->name('admin.unpaid');
    Route::post('deliveries-delete', 'DeliveryController@delete')->name('deliveries.delete');

    Route::get('admin-delivery-statuses', 'DeliveryController@statuses')->name('admin.statuses');

    Route::get('invoices', 'InvoiceController@index')->name('invoices.index');
    Route::get('get-invoices', 'InvoiceController@getInvoice')->name('get.invoices');
    Route::get('invoice/delete/{id}', 'InvoiceController@delete')->name('invoice.delete');
    Route::get('invoice/{id}', 'InvoiceController@show')->name('invoice.show');
    Route::post('delivery/invoice', 'InvoiceController@getInvoiceInfo')->name('delivery.invoice');
    Route::post('delivery/invoice/agent', 'InvoiceController@getInvoiceInfoAgent')->name('delivery.invoice.agent');
    Route::get('invoice/pdf-export/{id}', 'InvoiceController@export')->name('export.pdf');

    Route::resource('payment-requests', 'PaymentRequestsController');
    Route::get('get-payment-requests', 'PaymentRequestsController@getRequest');
    Route::post('admin.request.solve', 'PaymentRequestsController@solveRequest')->name('admin.request.solve');
    Route::post('admin.request.pending', 'PaymentRequestsController@pendingRequest')->name('admin.request.pending');

    Route::resource('authority-teams', 'AuthorityTeamController');

    Route::get('admin-contact', 'ContactController@index')->name('admin-contact');
    Route::post('admin-email-store', 'ContactController@emailStore')->name('admin-email.store');
    Route::post('admin-phone-store', 'ContactController@phoneStore')->name('admin-phone.store');
    Route::post('admin-address-store', 'ContactController@addressStore')->name('admin-address.store');
    Route::delete('admin-email-delete/{id}', 'ContactController@emailDestroy')->name('admin-email.destroy');
    Route::delete('admin-phone-delete/{id}', 'ContactController@phoneDestroy')->name('admin-phone.destroy');
    Route::delete('admin-address-delete/{id}', 'ContactController@addressDestroy')->name('admin-address.destroy');
    Route::get('admin-email-edit/{id}', 'ContactController@emailEdit')->name('admin-email.edit');
    Route::get('admin-phone-edit/{id}', 'ContactController@phoneEdit')->name('admin-phone.edit');
    Route::get('admin-address-edit/{id}', 'ContactController@addressEdit')->name('admin-address.edit');
    Route::put('admin-email-update/{id}', 'ContactController@emailUpdate')->name('admin-email.update');
    Route::put('admin-phone-update/{id}', 'ContactController@phoneUpdate')->name('admin-phone.update');
    Route::put('admin-address-update/{id}', 'ContactController@addressUpdate')->name('admin-address.update');

    Route::get('messages', 'PublicMessageController@index')->name('messages');

});

app/Models/InterCityRate.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class InterCityRate extends Model
{
    protected $guarded = [];

    public function cityRateCreatedBy(){
        return $this->belongsTo(User::class, 'created_by', 'id');
    }

    public function cityRateUpdatedBy(){
        return $this->belongsTo(User::class, 'updated_by', 'id');
    }

    public function cityRateDistrict(){
        return $this->belongsTo(District::class, 'district_id', 'id');
    }

    public function districtFrom()
    {
        return $this->belongsTo(District::class, 'district_id_from', 'id');
    }

    public function districtTo()
    {
        return $this->belongsTo(District::class, 'district_id_to', 'id');
    }
}

app/Http/Controllers/InterCityRateController.php
<?php

namespace App\Http\Controllers;

use App\Models\District;
use App\Models\InterCityRate;
use Illuminate\Http\Request;

class InterCityRateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = InterCityRate::orderBy('id', 'desc')
                                ->with('cityRateCreatedBy', 'cityRateUpdatedBy', 'districtFrom', 'districtTo')
                                ->get();

        $districts = District::orderBy('id', 'desc')->get();
        return view('layouts.backend.inter-city-rates.index', compact('data', 'districts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = new InterCityRate;
        $input = $request->except(['_token']);
        $input['created_by'] = auth()->user()->id;
        $input['updated_at'] = null;
        $input['district_id'] = $request->input('district_id_from');
        InterCityRate::create($input);
        return back()->with('success', 'Successfully Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\InterCityRate  $interCityRate
     * @return \Illuminate\Http\Response
     */
    public function show(InterCityRate $interCityRate)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\InterCityRate  $interCityRate
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = InterCityRate::find($id);
        $districts = District::orderBy('id', 'desc')->get();
        return view('layouts.backend.inter-city-rates.edit', compact('data', 'districts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\InterCityRate  $interCityRate
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->except(['_token', '_method']);
        $input['updated_by'] = auth()->user()->id;
        InterCityRate::where('id', $id)->update($input);
        return redirect()->route('admin-inter-city-rates.index')->with('success', 'Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\InterCityRate  $interCityRate
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        InterCityRate::where('id', $id)->delete();
        return back()->with('success', 'Successfully deleted');
    }
}

resources/views/layouts/backend/inter-city-rates/create-modal.blade.php
<div class="modal fade create" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    {{-- <div class="modal-dialog modal-lg modal-dialog-centered"> --}}
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Create Service</h5>
            <button style="color: white" type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          </div>


        <div class="modal-body">
            <form action="{{route('admin-inter-city-rates.store')}}" method="POST">
                @csrf
                    <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                        <label>From <span style="color: red">*</span></label>
                        <select style="width: 80%" class="select2" name="district_id_from" required>
                            @foreach ($districts as $district)
                            <option></option>
                                <option value="{{$district->id}}">{{$district->title}}</option>
                            @endforeach
                        </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                        <label>To <span style="color: red">*</span></label>
                        <select style="width: 80%" class="select2" name="district_id_to" required>
                            @foreach ($districts as $district)
                            <option></option>
                                <option value="{{$district->id}}">{{$district->title}}</option>
                            @endforeach
                        </select>
                        </div>
                    </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                            <label class="bmd-label-floating">Charge <span style="color: red">*</span></label>
                            <input name="charge" type="text" class="form-control" required>
                            </div>
                        </div>
                        </div>

                    <button type="submit" class="btn btn-primary pull-right">Create</button>
                    <div class="clearfix"></div>
            </form>
        {{-- form End--}}

        </div>
      </div>
    </div>
  </div>

resources/views/layouts/backend/inter-city-rates/delete-modal.blade.php
<div class="modal fade" tabindex="-1" role="dialog" id="confirm" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <p>Are you sure you want to delete this?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-danger" id="delete-btn">Delete</button>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/backend/inter-city-rates/edit.blade.php
@extends('layouts.backend.layouts.app')
@section('content')
    <div class="container-fluid">
      <div class="row">
        {{-- <div class="col-md-8"> --}}
          <div class="card">
            <div class="card-header card-header-info">
              <h4 class="card-title">Update City Rate</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('admin-inter-city-rates.update', $data->id) }}" method="POST">
                    {{ method_field('PUT') }}
                    {{ csrf_field() }}
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                <label class="bmd-label-floating">District From</label>
                                <select class="select2 col-md-6" name="district_id_from">
                                    @foreach ($districts as $district)
                                    <option></option>
                                    <option value="{{$district->id}}" {{ $district->id == $data->district_id_from ? 'selected' : '' }}>{{$district->title}}</option>
                                    @endforeach
                                </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                <label class="bmd-label-floating">District To</label>
                                <select class="select2 col-md-6" name="district_id_to">
                                    @foreach ($districts as $district)
                                    <option></option>
                                    <option value="{{$district->id}}" {{ $district->id == $data->district_id_to ? 'selected' : '' }}>{{$district->title}}</option>
                                    @endforeach
                                </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                <label class="bmd-label-floating">Charge</label>
                                <input value="{{$data->charge}}" name="charge" type="text" class="form-control">
                                </div>
                            </div>
                        </div>


                        <button type="submit" class="btn btn-primary pull-right">Update</button>
                        <a class="btn btn-danger pull-right" href="{{route('admin-inter-city-rates.index')}}">Back</a>
                        {{-- <button type="submit" class="btn btn-danger pull-right">Update</button> --}}
                        <div class="clearfix"></div>
                </form>
            </div>
          </div>
        {{-- </div> --}}
      </div>
    </div>


@endsection

resources/views/layouts/backend/inter-city-rates/index.blade.php
@extends('layouts.backend.layouts.app')
@section('content')
    <div class="container-fluid">
      <div class="row">
        {{-- <div class="col-md-8"> --}}
          <div class="card">
            @include('layouts.backend.home-component.home-component')
            <div class="card-body">
                <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target=".create">Create City Rate</button>
                <div class="clearfix"></div>
                <br>
                @php
                 $i = 1;
                @endphp
                <div class="table-responsive">
                <table class="table table-bordered table-hover" data-form="deleteForm">
                    <thead class="card-header-primary no-shadow">
                      <tr style="text-align: center">
                        <th scope="col">SL</th>
                        <th scope="col">From</th>
                        <th scope="col">To</th>
                        <th scope="col">Charge</th>
                        <th scope="col">Created At</th>
                        <th scope="col">Created By</th>
                        <th scope="col">Updated At</th>
                        <th scope="col">Updated By</th>
                        <th scope="col">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                    @foreach ($data as $row)
                        <tr style="text-align: center">
                            <td>{{$i++}}</td>
                            <td>{{$row->districtFrom['title']}}</td>
                            <td>{{$row->districtTo['title']}}</td>
                            <td>{{$row->charge}}</td>
                            <td>{{$row->created_at}}</td>
                            <td>{{$row->cityRateCreatedBy['name']}}</td>
                            <td>{{$row->updated_at}}</td>
                            <td>{{$row->cityRateUpdatedBy['name']}}</td>
                            <td class="td-actions">
                                <a class="btn btn-primary btn-link" href="{{ route('admin-inter-city-rates.edit', $row->id) }}">
                                    <i class="material-icons">edit</i>
                                </a>

                                <form class="form-delete" action="{{ route('admin-inter-city-rates.destroy', $row->id) }}" method="POST">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button type="submit" title="Delete" class="delete btn btn-danger btn-link">
                                        <i class="material-icons">close</i>
                                      </button>
                                </form>


                              </td>
                        </tr>
                    @endforeach
                      </tr>
                    </tbody>
                  </table>
                </div>
            </div>
          </div>
        {{-- </div> --}}
      </div>
    </div>


@include('layouts.backend.inter-city-rates.delete-modal')
@include('layouts.backend.inter-city-rates.create-modal')

@endsection

@push('scripts')

@endpush